package edu.cmu.deiis.analysis;

import edu.cmu.deiis.types.Annotation;

/**
 * An abstract factory that handles fields that the different kinds of annotations
 * have in common
 * @author yueran
 *
 */
public abstract class AbstractAnnotationFactory {
  protected String annotatorName;
  protected boolean completelyConfident; // whether the annotator use probabilities 
  
  /**
   * 
   * @param annotatorName       Name for the CasProcessorId field of annotations generated by this class
   * @param completelyConfident True means there is only one answer to what we are annotating
   *                            Example: parsing with regex, merging tokens with ngram
   */
  public AbstractAnnotationFactory(String annotatorName, boolean completelyConfident) {
    this.completelyConfident = completelyConfident;
    this.annotatorName = annotatorName;
  }
  
  /**
   * Completely confident defaults to false
   * @param annotatorName       Name for the CasProcessorId field of annotations generated by this class
   */
  public AbstractAnnotationFactory(String annotatorName) {
    this.completelyConfident = false;
    this.annotatorName = annotatorName;
  }
  
  /**
   * A helper method to fill in parts of an annotation that all annotations have in common and adds
   * the annotation to the index.
   * @param annotation      The partially filled annotation
   * @param begin           The starting position for the annotation
   * @param end             The ending position for the annotation
   * @param confidence      The confidence with which we generated this annotation
   */
  public void AnnotationHelper(Annotation annotation, int begin, int end, double confidence) {
    annotation.setBegin(begin);
    annotation.setEnd(end);
    annotation.setCasProcessorId(annotatorName);
    annotation.setConfidence(confidence);
    annotation.addToIndexes();
  }
  
  /**
   * A helper method to fill in parts of an annotation that all annotations have in common and adds
   * the annotation to the index.
   * Confidence field of the annotation is 1 if the annotator is completely confident.
   * Otherwise, the confidence is set to the default value from the CAS (possibly undefined).
   * @param annotation      The partially filled annotation
   * @param begin           The starting position for the annotation
   * @param end             The ending position for the annotation
   */
  public void AnnotationHelper(Annotation annotation, int begin, int end) {
    annotation.setBegin(begin);
    annotation.setEnd(end);
    annotation.setCasProcessorId(annotatorName);
    if (completelyConfident) {
      annotation.setConfidence(1.0);
    }
    annotation.addToIndexes();
  }

}
