package edu.cmu.deiis.analysis;

import org.apache.uima.analysis_component.JCasAnnotator_ImplBase;
import org.apache.uima.analysis_engine.AnalysisEngineProcessException;
import org.apache.uima.jcas.JCas;


/**
 * Aggregates the answer scores generated by earlier parts of the pipeline
 * The ultimate answer score is created from the a sum of the previous scores weighted by
 * the confidence
 * @author yueran
 *
 */
public class AggregateAnswerScoreAnnotator extends JCasAnnotator_ImplBase {
  
  protected static TestElementAggregateScoringProcessor processor = 
          new TestElementAggregateScoringProcessor();
  
  /**
   * just a wrapper for TestElementAggregateScoringProcessor.process
   * This is so that the processor could inherit from an abstract class
   */
  public void process(JCas aJCas) throws AnalysisEngineProcessException {
    processor.process(aJCas);
  }
}